#!/usr/bin/env python3
"""Write the whole shortlist out for the tuner, and the morph into a page.

  design/cut-title/morph/faces.json   all of them, for the tuner, which is the
                                  only thing that ever fetches it.
  --site <file>                   the chosen face only, in that file's marked
                                  block: one face and not twenty-four, about
                                  25 KB against 700.

    python build-site.py --face hostgrotesk

THERE IS NO SITE TO WRITE INTO TODAY, which is why --site has no default. The
morph was the hand-written /portfolio's, in portfolio/cut-morph.js, and #141
deleted that tree without porting it — the Front Screen ships the cut title as
one baked picture (design/cut-title/build-cut-title.py) and never morphs it.
Whichever ticket brings the morph back points this at the file it lands in; the
lab is whole in the meantime and the tuner is what it is for.

The fonts are not in this repository. Run it beside `friz/`, `gf/` and `fsf/` as
design/cut-title/morph/README.md describes; without them there is nothing to
build from.
"""
import argparse, json, pathlib, sys, warnings
warnings.filterwarnings("ignore")
import lib, curated, morph

# design/bake/ is three folders up and is not a package, so it is put on the path
# rather than imported through a name that does not exist. It holds WHICH FACE -
# design/bake/morph/recipe.json - so the Editor and a bare re-run of this script
# agree about the answer, which is the whole of what the sidecar is for. See
# design/bake/tuning.py.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[3] / "design" / "bake"))
import tuning

TUNING = tuning.bake("morph")

REPO = pathlib.Path(__file__).resolve()
BEGIN = "/* cut-morph:data begin — generated by design/cut-title/morph/build-site.py */"
END = "/* cut-morph:data end */"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--face", default=TUNING.text("face"),
                    help="slug of the face a page would use; the default is the "
                         "one design/bake/morph/ names, so a bare re-run keeps it")
    ap.add_argument("--repo", type=pathlib.Path, required=True,
                    help="the worktree to write faces.json into")
    ap.add_argument("--site", type=pathlib.Path, default=None,
                    help="a file with the cut-morph:data markers in it, to write "
                         "the chosen face into. Nothing has them today")
    args = ap.parse_args()

    friz, top, bot = curated.reference()
    faces = curated.build_all(friz, top)
    if not faces: sys.exit("nothing built")

    friz_true = morph.true_path(friz, top)
    doc = dict(
        viewBox=f"0 0 {friz['span']:g} {top-bot:g}",
        friz=friz_true,
        faces=faces,
        frizmeta=dict(stem=friz["stem"]/curated.CAP, span=friz["span"],
                      track_em=0.02, cap=curated.CAP),
    )

    out = args.repo / "design" / "cut-title" / "morph" / "faces.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, separators=(",", ":")), encoding="utf-8")
    print(f"\nwrote {out.relative_to(args.repo)}  "
          f"({len(out.read_bytes())/1024:.0f} KB, {len(faces)} faces)")

    if args.site is None: return

    pick = next((f for f in faces if f["slug"] == args.face), None)
    if pick is None:
        sys.exit(f"no such face: {args.face}\n  have: "
                 + ", ".join(f["slug"] for f in faces))

    # Only what the runtime reads. The blurb, the metrics and the other
    # twenty-three faces are the tuner's business and have no place in the page.
    site = dict(slug=pick["slug"], name=pick["name"],
                letters=[{k: l[k] for k in ("ch", "a", "b", "t")} for l in pick["letters"]])
    block = (f"{BEGIN}\n"
             f"  var FRIZ = {json.dumps(friz_true, separators=(',', ':'))};\n"
             f"  var FACE = {json.dumps(site, separators=(',', ':'))};\n"
             f"  {END}")

    js = args.site
    src = js.read_text(encoding="utf-8")
    head, sep, rest = src.partition(BEGIN)
    body, sep2, tail = rest.partition(END)
    if not sep or not sep2:
        sys.exit(f"markers not found in {js}\n  {BEGIN}\n  {END}")
    assert "</script" not in block, "data would close the script tag"
    js.write_text(head + block + tail, encoding="utf-8")
    print(f"wrote {js}  "
          f"({len(js.read_bytes())/1024:.0f} KB total, face: {pick['name']})")
    print(f"  score {pick['score']:.3f}   weight {pick['wght']}   "
          f"tracking {pick['track_em']:+.4f} em   kerned {pick['kerned']}/7")


if __name__ == "__main__":
    main()
