#!/usr/bin/env python3
"""Write the morph into the site, and the whole shortlist out for the tuner.

Two artifacts, one run, because they have to agree:

  portfolio/cut-morph.js          the chosen face only, in the marked block.
                                  This is what ships, so it carries one face and
                                  not twenty-four -- about 25 KB against 700.
  design/cut-title/morph/faces.json   all of them, for the tuner, which is the
                                  only thing that ever fetches it.

    python build-site.py --face satoshi

The fonts are not in this repository. Run it beside `friz/`, `gf/` and `fsf/` as
design/cut-title/morph/README.md describes; without them there is nothing to
build from and the block already in cut-morph.js is the artifact of record.
"""
import argparse, json, pathlib, sys, warnings
warnings.filterwarnings("ignore")
import lib, curated, morph

REPO = pathlib.Path(__file__).resolve()
BEGIN = "/* cut-morph:data begin — generated by design/cut-title/morph/build-site.py */"
END = "/* cut-morph:data end */"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--face", default="satoshi", help="slug of the face the site uses")
    ap.add_argument("--repo", type=pathlib.Path, required=True,
                    help="the worktree to write into")
    ap.add_argument("--faces-only", action="store_true",
                    help="write faces.json and leave cut-morph.js alone")
    args = ap.parse_args()

    friz, top, bot = curated.reference()
    faces = curated.build_all(friz, top)
    if not faces: sys.exit("nothing built")

    friz_true = morph.true_path(friz, top)
    doc = dict(
        viewBox=f"0 0 {friz['span']:g} {top-bot:g}",
        friz=friz_true,
        faces=faces,
        frizmeta=dict(stem=friz["stem"]/curated.CAP, span=friz["span"],
                      track_em=0.02, cap=curated.CAP),
    )

    out = args.repo / "design" / "cut-title" / "morph" / "faces.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, separators=(",", ":")), encoding="utf-8")
    print(f"\nwrote {out.relative_to(args.repo)}  "
          f"({len(out.read_bytes())/1024:.0f} KB, {len(faces)} faces)")

    if args.faces_only: return

    pick = next((f for f in faces if f["slug"] == args.face), None)
    if pick is None:
        sys.exit(f"no such face: {args.face}\n  have: "
                 + ", ".join(f["slug"] for f in faces))

    # Only what the runtime reads. The blurb, the metrics and the other
    # twenty-three faces are the tuner's business and have no place in the page.
    site = dict(slug=pick["slug"], name=pick["name"],
                letters=[{k: l[k] for k in ("ch", "a", "b", "t")} for l in pick["letters"]])
    block = (f"{BEGIN}\n"
             f"  var FRIZ = {json.dumps(friz_true, separators=(',', ':'))};\n"
             f"  var FACE = {json.dumps(site, separators=(',', ':'))};\n"
             f"  {END}")

    js = args.repo / "portfolio" / "cut-morph.js"
    src = js.read_text(encoding="utf-8")
    head, sep, rest = src.partition(BEGIN)
    body, sep2, tail = rest.partition(END)
    if not sep or not sep2:
        sys.exit(f"markers not found in {js}\n  {BEGIN}\n  {END}")
    assert "</script" not in block, "data would close the script tag"
    js.write_text(head + block + tail, encoding="utf-8")
    print(f"wrote {js.relative_to(args.repo)}  "
          f"({len(js.read_bytes())/1024:.0f} KB total, face: {pick['name']})")
    print(f"  score {pick['score']:.3f}   weight {pick['wght']}   "
          f"tracking {pick['track_em']:+.4f} em   kerned {pick['kerned']}/7")


if __name__ == "__main__":
    main()
